"""Text shared by all generated reports."""

DISCLAIMER = (
    "This report is generated by software as a design aid. Results must be reviewed, verified and "
    "signed by a qualified structural engineer before use for construction."
)
