"""Excel workbook and PDF report generation."""

from __future__ import annotations

import datetime as _dt
from typing import Optional

from .. import APP_NAME, COMPANY, __version__
from ..core.beamcalc import eighth_points
from ..core.frame import FrameAnalysis, FrameModel
from ..core.model import Project
from ..core.plan_engine import PlanResult
from ..design.runner import DesignReport

DISCLAIMER = ("This report is generated by software as a design aid. Results must be reviewed, verified and "
              "signed by a qualified structural engineer before use for construction.")


# =========================================================================== Excel
def write_excel(path: str, project: Project, plan_results: dict[str, PlanResult],
                fm: Optional[FrameModel] = None, fa: Optional[FrameAnalysis] = None,
                rep: Optional[DesignReport] = None, watermark: str = "") -> str:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    head_fill = PatternFill("solid", fgColor="1F3A5F")
    head_font = Font(color="FFFFFF", bold=True)
    bad_fill = PatternFill("solid", fgColor="F8D7DA")

    def sheet(title, headers, rows, bad_col: Optional[int] = None):
        ws = wb.create_sheet(title[:31])
        ws.append(headers)
        for c in ws[1]:
            c.fill, c.font = head_fill, head_font
            c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        for r in rows:
            ws.append([round(v, 3) if isinstance(v, float) else v for v in r])
            if bad_col is not None and r[bad_col] in (False, "FAIL", "NO"):
                for c in ws[ws.max_row]:
                    c.fill = bad_fill
        for i, h in enumerate(headers, 1):
            width = max([len(str(h))] + [len(str(r[i - 1])) for r in rows[:200]] + [8])
            ws.column_dimensions[get_column_letter(i)].width = min(width + 2, 45)
        ws.freeze_panes = "A2"
        return ws

    ws = wb.active
    ws.title = "Summary"
    ws.append([f"{APP_NAME} {__version__} – {COMPANY}"])
    ws["A1"].font = Font(size=14, bold=True)
    info = [("Project", project.name), ("Client", project.client), ("Engineer", project.engineer),
            ("Location", project.location), ("Date", _dt.date.today().isoformat()),
            ("Seismic zone", project.seismic.zone), ("Wind city / Vb", f"{project.wind.city} / {project.wind.basic_speed} m/s"),
            ("Height (m)", round(project.elevations()[-1], 3)), ("Levels", len(project.levels))]
    if watermark:
        info.append(("Licence", watermark))
    for k, v in info:
        ws.append([k, v])
    ws.append([])
    ws.append([DISCLAIMER])
    ws.column_dimensions["A"].width = 22
    ws.column_dimensions["B"].width = 50

    rows = []
    for pname, pr in plan_results.items():
        rows.append((pname, pr.applied["D"], pr.applied["L"], pr.reacted["D"], pr.reacted["L"], pr.imbalance_pct,
                     len(pr.errors), len(pr.warnings)))
    sheet("Plan checks", ["Plan", "Applied DL kN", "Applied LL kN", "Reaction DL kN", "Reaction LL kN",
                          "Imbalance %", "Errors", "Warnings"], rows)
    rows = []
    for pname, pr in plan_results.items():
        plan = project.plan(pname)
        marks = {o.id: o.mark for o in (plan.columns + plan.beams + plan.slabs)} if plan else {}
        for cl in pr.columns.values():
            rows.append((pname, cl.mark, cl.dead, cl.live, cl.total))
    sheet("Column loads (plan)", ["Plan", "Column", "Dead kN", "Live kN", "Total kN"], rows)
    rows = []
    for pname, pr in plan_results.items():
        plan = project.plan(pname)
        bmap = {b.id: b for b in plan.beams} if plan else {}
        for bid, br in pr.beams.items():
            b = bmap.get(bid)
            if not b:
                continue
            dia = br.diagram(True)
            pts = eighth_points(br.length, dia)
            rows.append((pname, b.mark, br.length, b.b, b.d, br.total("D"), br.total("L"), br.equivalent_udl(),
                         *[p["M"] for p in pts], max(abs(p["V"]) for p in pts)))
    sheet("Beam loads (plan)", ["Plan", "Beam", "Span m", "b m", "D m", "Total DL kN", "Total LL kN", "Eq. UDL kN/m",
                                *[f"Mu @{k}/8 kNm" for k in range(9)], "Vu max kN"], rows)
    issues = []
    for pname, pr in plan_results.items():
        for i in pr.issues:
            issues.append((pname, i.level, i.kind, i.message))
    if fm:
        for i in fm.issues:
            issues.append(("Frame", i.level, i.kind, i.message))
    sheet("Issues", ["Where", "Level", "Type", "Message"], issues)
    if fa and fm:
        rows = []
        for nid, nd in fm.nodes.items():
            if not nd.support:
                continue
            for c in fa.combos:
                r = fa.reaction(nid, c.factors)
                rows.append((nd.tag, c.name, *[float(v) for v in r]))
        sheet("Support reactions", ["Column", "Combination", "FX kN", "FY kN", "FZ kN", "MX kNm", "MY kNm", "MZ kNm"], rows)
        rows = [(k, r.T, r.sa_g, r.Ah, r.W, r.Vb) for k, r in fm.seismic.items()]
        if rows:
            sheet("Seismic", ["Direction", "T s", "Sa/g", "Ah", "W kN", "VB kN"], rows)
        rows = []
        for k, r in fm.wind.items():
            for i, f in enumerate(r.forces):
                if f:
                    rows.append((k, fm.levels[i].name, r.pressures[i], f))
        if rows:
            sheet("Wind", ["Direction", "Level", "pd kN/m2", "Storey force kN"], rows)
    if rep:
        sheet("Beam design", ["Level", "Beam", "b m", "D m", "Span m", "Mu+ kNm", "Mu- left", "Mu- right", "Vu kN",
                              "Bottom", "Top left", "Top right", "Stirrups", "OK", "Notes"],
              [(b.level, b.mark, b.b, b.d, b.span, b.M_sag, b.M_hog_l, b.M_hog_r, b.V_max, b.bottom, b.top_l, b.top_r,
                b.stirrups, "YES" if b.ok else "NO", "; ".join(b.notes)) for b in rep.beams], bad_col=13)
        sheet("Column design", ["Level", "Column", "b m", "D m", "Pu kN", "Mux kNm", "Muy kNm", "Steel %", "Bars",
                                "Ties", "Governing", "Interaction", "OK", "Notes"],
              [(c.level, c.mark, c.b, c.d, c.Pu, c.Mux, c.Muy, c.steel_pct, c.bars, c.ties, c.governing, c.utilisation,
                "YES" if c.ok else "NO", "; ".join(c.notes)) for c in rep.columns], bad_col=12)
        sheet("Footing design", ["Column", "P service kN", "L m", "B m", "D m", "Bars along L", "Bars along B",
                                 "q kN/m2", "OK", "Notes"],
              [(f.mark, f.P_service, f.L, f.B, f.D, f.bars_L, f.bars_B, f.q, "YES" if f.ok else "NO", "; ".join(f.notes))
               for f in rep.footings], bad_col=8)
        sheet("Slab design", ["Plan", "Slab", "lx m", "ly m", "Type", "D mm", "Mx+ kNm/m", "My+ kNm/m", "M- kNm/m",
                              "Short span", "Long span", "Support (top)", "OK", "Notes"],
              [(pn, s.mark, s.lx, s.ly, s.kind, s.D_mm, s.Mx_pos, s.My_pos, s.M_neg, s.ast_x, s.ast_y, s.ast_neg,
                "YES" if s.ok else "NO", "; ".join(s.notes)) for pn, s in rep.slabs], bad_col=12)
        sheet("Drift", ["Case", "Level", "Drift mm", "Ratio", "OK (<=0.004)"],
              [(d["case"], d["level"], d["drift_mm"], d["ratio"], "YES" if d["ok"] else "NO") for d in rep.drifts], bad_col=4)
        boq = rep.boq
        sheet("BOQ & Cost", ["Item", "Unit", "Quantity", "Rate (INR)", "Amount (INR)"],
              list(boq.get("lines", [])) + [("TOTAL", "", "", "", boq.get("cost", 0.0)),
                                            ("Steel / concrete", "kg/m³", boq.get("steel_per_m3", 0.0), "", "")])
    wb.save(path)
    return path


# =========================================================================== PDF
def write_pdf(path: str, project: Project, plan_results: dict[str, PlanResult],
              fm: Optional[FrameModel] = None, rep: Optional[DesignReport] = None, watermark: str = "") -> str:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(path, pagesize=landscape(A4), leftMargin=12 * mm, rightMargin=12 * mm,
                            topMargin=14 * mm, bottomMargin=14 * mm, title=f"{project.name} – {APP_NAME}")
    story = []

    def table(headers, rows, widths=None):
        body = [[(f"{v:.2f}" if isinstance(v, float) else str(v)) for v in r] for r in rows]
        data = ([headers] if headers else []) + body
        t = Table(data, repeatRows=1 if headers else 0, colWidths=widths)
        st = [("FONTSIZE", (0, 0), (-1, -1), 7.5), ("GRID", (0, 0), (-1, -1), 0.25, colors.grey)]
        if headers:
            st += [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F3A5F")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                   ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F5F9")])]
        else:
            st += [("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8EDF3")), ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#E8EDF3"))]
        for i, r in enumerate(rows, start=1 if headers else 0):
            if any(v in ("NO", "FAIL") for v in r):
                st.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#F8D7DA")))
        t.setStyle(TableStyle(st))
        return t

    story.append(Paragraph(f"<b>{project.name}</b>", styles["Title"]))
    story.append(Paragraph(f"Structural pre-processing, analysis &amp; design report – {APP_NAME} {__version__}", styles["Normal"]))
    if watermark:
        story.append(Paragraph(f"<font color='red'><b>{watermark}</b></font>", styles["Normal"]))
    story.append(Spacer(1, 6 * mm))
    meta = [["Client", project.client or "-", "Engineer", project.engineer or "-"],
            ["Location", project.location or "-", "Date", _dt.date.today().isoformat()],
            ["Seismic", f"Zone {project.seismic.zone}, I={project.seismic.importance}, R={project.seismic.response_reduction}, {project.seismic.soil} soil",
             "Wind", f"{project.wind.city}: Vb {project.wind.basic_speed} m/s, terrain {project.wind.terrain}"],
            ["Codes", "IS 456:2000, IS 875 (Parts 1-3), IS 1893 (Part 1):2016", "Height", f"{project.elevations()[-1]:.2f} m"]]
    story.append(table(None, meta))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(DISCLAIMER, styles["Italic"]))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("Load take-down check (PlanWin)", styles["Heading2"]))
    story.append(table(["Plan", "Applied DL", "Applied LL", "Reaction DL", "Reaction LL", "Imbalance %", "Errors"],
                       [(n, r.applied["D"], r.applied["L"], r.reacted["D"], r.reacted["L"], r.imbalance_pct, len(r.errors))
                        for n, r in plan_results.items()]))
    if fm and (fm.seismic or fm.wind):
        story.append(Paragraph("Lateral loads", styles["Heading2"]))
        rows = [(k, r.T, r.sa_g, f"{r.Ah:.4f}", r.W, r.Vb) for k, r in fm.seismic.items()]
        if rows:
            story.append(table(["Dir", "T (s)", "Sa/g", "Ah", "W (kN)", "VB (kN)"], rows))
        rows = [(k, sum(r.forces)) for k, r in fm.wind.items()]
        if rows:
            story.append(Spacer(1, 3 * mm))
            story.append(table(["Wind dir", "Base shear (kN)"], rows))
    if rep:
        story.append(PageBreak())
        story.append(Paragraph("Column design (IS 456 cl 39.6 biaxial)", styles["Heading2"]))
        story.append(table(["Level", "Col", "b x D (mm)", "Pu kN", "Mux", "Muy", "p %", "Bars", "Ties", "Ratio", "OK"],
                           [(c.level, c.mark, f"{c.b * 1000:.0f}x{c.d * 1000:.0f}", c.Pu, c.Mux, c.Muy, c.steel_pct, c.bars,
                             c.ties, c.utilisation, "YES" if c.ok else "NO") for c in rep.columns]))
        story.append(PageBreak())
        story.append(Paragraph("Beam design", styles["Heading2"]))
        story.append(table(["Level", "Beam", "b x D", "Span", "Mu+", "Mu- L", "Mu- R", "Vu", "Bottom", "Top L", "Top R",
                            "Stirrups", "OK"],
                           [(b.level, b.mark, f"{b.b * 1000:.0f}x{b.d * 1000:.0f}", b.span, b.M_sag, b.M_hog_l, b.M_hog_r,
                             b.V_max, b.bottom, b.top_l, b.top_r, b.stirrups, "YES" if b.ok else "NO") for b in rep.beams]))
        story.append(PageBreak())
        story.append(Paragraph("Footing design (isolated)", styles["Heading2"]))
        story.append(table(["Col", "P (kN)", "L x B x D (m)", "Bars along L", "Bars along B", "q (kN/m²)", "OK"],
                           [(f.mark, f.P_service, f"{f.L:.2f} x {f.B:.2f} x {f.D:.2f}", f.bars_L, f.bars_B, f.q,
                             "YES" if f.ok else "NO") for f in rep.footings]))
        story.append(Spacer(1, 5 * mm))
        story.append(Paragraph("Slab design", styles["Heading2"]))
        story.append(table(["Plan", "Slab", "lx x ly", "Type", "D mm", "Short", "Long", "Top", "OK"],
                           [(pn, s.mark, f"{s.lx:.2f} x {s.ly:.2f}", s.kind, s.D_mm, s.ast_x, s.ast_y, s.ast_neg,
                             "YES" if s.ok else "NO") for pn, s in rep.slabs]))
        story.append(PageBreak())
        story.append(Paragraph("Quantities &amp; cost estimate", styles["Heading2"]))
        story.append(table(["Item", "Unit", "Qty", "Rate", "Amount"], list(rep.boq.get("lines", []))
                           + [("TOTAL", "", "", "", rep.boq.get("cost", 0.0))]))
        if rep.warnings:
            story.append(Spacer(1, 4 * mm))
            story.append(Paragraph("Warnings", styles["Heading2"]))
            for w in rep.warnings:
                story.append(Paragraph(f"• {w}", styles["Normal"]))

    def footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.drawString(12 * mm, 8 * mm, f"{APP_NAME} {__version__} – {COMPANY}   {watermark}")
        canvas.drawRightString(landscape(A4)[0] - 12 * mm, 8 * mm, f"Page {_doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return path
