"""Text shared by all generated reports."""

DISCLAIMER = (
    "This report is generated by software as a design aid. Results must be reviewed, verified and "
    "signed by a qualified structural engineer before use for construction."
)


def literal_text(wb, columns: set[int] | None = None) -> int:
    """Store text that starts with ``=`` as text, not as a formula.

    openpyxl writes any string beginning with ``=`` as a formula, so a project, plan or member
    named "=Tower" (or text injected through an import or the AI) would become a formula –
    Excel then reports a damaged file, or worse, evaluates it.  Workbooks without formulas of
    their own call this with ``columns=None`` (every cell); the BOQ workbook, whose own
    formulas never sit in column A, passes ``{1}``.  Returns the number of cells fixed."""
    n = 0
    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for c in row:
                if c.data_type == "f" and (columns is None or c.column in columns):
                    c.data_type = "s"
                    n += 1
    return n
