"""STAAD.Pro input file (.std) writer.

Coordinates use STAAD's default Y-up system: STAAD (X, Y, Z) = plan
(x, z, -y), a proper rotation, so plan views appear un-mirrored.
Per Bentley's documentation, for vertical members with BETA 0 the local z
axis is parallel to global Z, so columns get ``BETA = angle``
with YD = b and ZD = d.  Beams use YD = depth, ZD = width.

All loads are exported explicitly (self-weight included in member loads),
so no SELFWEIGHT command is generated – this mirrors PlanWin's behaviour
of passing exactly the loads it computed.
"""

from __future__ import annotations

import datetime as _dt
import math
from collections import defaultdict

from .. import APP_NAME, __version__
from ..core.frame import FrameModel, is_combinations
from ..core.model import grade_fck
from ..core.solver import MLoad, MPoint, MTorque

# LOADTYPE is optional in STAAD; seismic keywords differ between V8i ("Seismic") and
# CONNECT ("Seismic-H"), so seismic cases are written without LOADTYPE for portability.
_TYPES = {
    "DL": ("Dead", "DEAD LOAD"),
    "LL": ("Live", "LIVE LOAD"),
    "WLX": ("Wind", "WIND X"),
    "WLY": ("Wind", "WIND Y"),
    "EQX": ("", "SEISMIC X (IS 1893 STATIC)"),
    "EQY": ("", "SEISMIC Y (IS 1893 STATIC)"),
    "ETX": ("", "ACCIDENTAL TORSION X"),
    "ETY": ("", "ACCIDENTAL TORSION Y"),
}


def _f(v: float) -> str:
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _text(s: str, n: int) -> str:
    """Free text for the job information: ``;`` separates STAAD commands, so it becomes ``,``."""
    return " ".join(str(s).replace(";", ",").split())[:n]


def _ranges(ids: list[int]) -> str:
    ids = sorted(ids)
    out, i = [], 0
    while i < len(ids):
        j = i
        while j + 1 < len(ids) and ids[j + 1] == ids[j] + 1:
            j += 1
        out.append(f"{ids[i]} TO {ids[j]}" if j - i >= 2 else " ".join(str(k) for k in ids[i : j + 1]))
        i = j + 1
    return " ".join(out)


def _wrap(prefix: str, body: str, width: int = 70) -> list[str]:
    words = body.split()
    lines, cur = [], prefix
    for w in words:
        if len(cur) + len(w) + 1 > width:
            lines.append(cur + " -")
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    lines.append(cur)
    return lines


def write_staad(fm: FrameModel, path: str, engineer: str = "", watermark: str = "") -> str:
    p = fm.p
    L = []
    L.append("STAAD SPACE")
    L.append("START JOB INFORMATION")
    L.append(f"JOB NAME {_text(p.name, 60)}")
    if p.client:
        L.append(f"JOB CLIENT {_text(p.client, 60)}")
    if engineer or p.engineer:
        L.append(f"ENGINEER NAME {_text(engineer or p.engineer, 40)}")
    L.append(f"ENGINEER DATE {_dt.date.today().strftime('%d-%b-%y')}")
    L.append("END JOB INFORMATION")
    L.append(f"* Generated by {APP_NAME} {__version__}" + (f"  [{watermark}]" if watermark else ""))
    nodal, diaphragms = fm.export_model()
    if fm.rs:
        L.append("* Seismic method: response spectrum (IS 1893-1 cl 7.7). EQX/EQY below")
        L.append("* are the equivalent storey forces of the scaled spectral storey")
        L.append("* shears; define a SPECTRUM case to re-run RSA.")
    if any(m.kind == "wall" for m in fm.members.values()):
        L.append("* Shear walls are modelled as wide columns joined to their ends by")
        L.append("* rigid links (1 x 1 m).")
    L.append("INPUT WIDTH 79")
    L.append("UNIT METER KN")
    L.append("JOINT COORDINATES")
    used = {n for m in fm.members.values() for n in (m.n1, m.n2)} | {n.id for n in fm.nodes.values() if n.support}
    nid_map = {nid: k for k, nid in enumerate(sorted(used), start=1)}
    for nid in sorted(used):
        n = fm.nodes[nid]
        L.append(f"{nid_map[nid]} {_f(n.x)} {_f(n.z)} {_f(-n.y)};")
    L.append("MEMBER INCIDENCES")
    mid_map = {mid: k for k, mid in enumerate(sorted(fm.members), start=1)}
    for mid in sorted(fm.members):
        m = fm.members[mid]
        L.append(f"{mid_map[mid]} {nid_map[m.n1]} {nid_map[m.n2]};")
    # materials
    grades = sorted({m.grade for m in fm.members.values()}, key=grade_fck)
    L.append("DEFINE MATERIAL START")
    for g in grades:
        fck = grade_fck(g)
        L.append(f"ISOTROPIC CONCRETE_{g}")
        L.append(f"E {_f(5000 * math.sqrt(fck) * 1000)}")
        L.append("POISSON 0.2")
        L.append("DENSITY 25")
        L.append("ALPHA 1e-05")
        L.append("DAMP 0.05")
        L.append("TYPE CONCRETE")
        L.append(f"STRENGTH FCU {_f(fck * 1000)}")
    L.append("END DEFINE MATERIAL")
    # properties grouped by size; explicit AX/IX/IY/IZ carry the cracked-section
    # modifiers (IS 1893 cl 6.4.3.1) and the reduced torsion constant used internally
    props = defaultdict(list)
    for mid, m in fm.members.items():
        yd, zd = (m.d, m.b) if m.kind in ("beam", "link") else (m.b, m.d)
        props[(yd, zd, round(m.i_factor, 3), round(m.torsion_factor, 3))].append(mid_map[mid])
    L.append("MEMBER PROPERTY INDIAN")
    for (yd, zd, fi, ft), ids in sorted(props.items()):
        iz = fi * zd * yd**3 / 12.0
        iy = fi * yd * zd**3 / 12.0
        a_, c_ = max(yd, zd), min(yd, zd)
        j = ft * (1 / 3 - 0.21 * (c_ / a_) * (1 - (c_ / a_) ** 4 / 12)) * a_ * c_**3
        L.extend(
            _wrap(
                "", f"{_ranges(ids)} PRIS AX {yd * zd:.6g} IX {j:.6g} IY {iy:.6g} IZ {iz:.6g} YD {_f(yd)} ZD {_f(zd)}"
            )
        )
    L.append("CONSTANTS")
    by_grade = defaultdict(list)
    for mid, m in fm.members.items():
        by_grade[m.grade].append(mid_map[mid])
    for g, ids in by_grade.items():
        L.extend(_wrap("", f"MATERIAL CONCRETE_{g} MEMB {_ranges(ids)}"))
    betas = defaultdict(list)
    for mid, m in fm.members.items():
        if m.kind in ("column", "wall") and abs(m.angle) > 1e-6:
            betas[round(m.angle, 3)].append(mid_map[mid])
    for ang, ids in betas.items():
        L.extend(_wrap("", f"BETA {_f(ang)} MEMB {_ranges(ids)}"))
    L.append("SUPPORTS")
    fixed = [nid_map[n.id] for n in fm.nodes.values() if n.support == "fixed"]
    pinned = [nid_map[n.id] for n in fm.nodes.values() if n.support == "pinned"]
    if fixed:
        L.extend(_wrap("", f"{_ranges(fixed)} FIXED"))
    if pinned:
        L.extend(_wrap("", f"{_ranges(pinned)} PINNED"))
    # rigid floor diaphragms: in-plane (global ZX in STAAD's Y-up system) slaved to one floor joint
    for _lvl, (master, slaves) in sorted(diaphragms.items()):
        if slaves:
            L.extend(_wrap("", f"SLAVE ZX MASTER {nid_map[master]} JOINT {_ranges([nid_map[n] for n in slaves])}"))
    cases = fm.cases()
    for k, case in enumerate(cases, start=1):
        typ, title = _TYPES[case]
        L.append(f"LOAD {k} LOADTYPE {typ} TITLE {title}" if typ else f"LOAD {k} TITLE {title}")
        mlines, jlines = [], []
        for mid in sorted(fm.members):
            m = fm.members[mid]
            for ld in m.loads.get(case, []):
                if isinstance(ld, MLoad):
                    w1, w2 = ld.w1[2], ld.w2[2]  # global Z (gravity) components -> STAAD GY
                    if abs(w1) < 1e-9 and abs(w2) < 1e-9:
                        continue
                    if abs(w1 - w2) < 1e-6:
                        mlines.append(f"{mid_map[mid]} UNI GY {_f(w1)} {_f(ld.a)} {_f(ld.b)}")
                    else:
                        mlines.append(f"{mid_map[mid]} TRAP GY {_f(w1)} {_f(w2)} {_f(ld.a)} {_f(ld.b)}")
                elif isinstance(ld, MPoint) and abs(ld.P[2]) > 1e-9:
                    mlines.append(f"{mid_map[mid]} CON GY {_f(ld.P[2])} {_f(ld.x)}")
                elif isinstance(ld, MTorque) and (abs(ld.t1) > 1e-9 or abs(ld.t2) > 1e-9):
                    # uniform moment about the member's local x axis (torsion), averaged over its length
                    mlines.append(f"{mid_map[mid]} UMOM X {_f((ld.t1 + ld.t2) / 2)} {_f(ld.a)} {_f(ld.b)}")
        for nid, vec in nodal.get(case, {}).items():
            if nid not in nid_map:
                continue
            # plan (X, Y, Z-up) -> STAAD (X, Y-up, Z = -Y) for forces and moments alike
            comps = []
            for key, val in (
                ("FX", vec[0]),
                ("FY", vec[2]),
                ("FZ", -vec[1]),
                ("MX", vec[3]),
                ("MY", vec[5]),
                ("MZ", -vec[4]),
            ):
                if abs(val) > 1e-9:
                    comps.append(f"{key} {_f(val)}")
            if comps:
                jlines.append(f"{nid_map[nid]} {' '.join(comps)}")
        if mlines:
            L.append("MEMBER LOAD")
            L.extend(mlines)
        if jlines:
            L.append("JOINT LOAD")
            L.extend(jlines)
    combos = is_combinations(p.seismic.enabled, p.wind.enabled, "ETX" in cases)
    idx = {c: k for k, c in enumerate(cases, start=1)}
    for j, c in enumerate([c for c in combos if c.kind == "ultimate"], start=101):
        L.append(f"LOAD COMB {j} {c.name}")
        L.append(" ".join(f"{idx[k]} {_f(v)}" for k, v in c.factors.items() if k in idx))
    L.append("PERFORM ANALYSIS")
    L.append("FINISH")
    with open(path, "w", encoding="ascii", errors="replace", newline="\r\n") as f:
        f.write("\n".join(L) + "\n")
    return path
